# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-08 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_question_option1_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='No_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
