# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-08 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_question_no_of_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='No_of_votes',
            new_name='no_of_votes',
        ),
    ]
