# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-11 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180808_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option1_percentage',
            new_name='option1_votes',
        ),
    ]
