# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-12 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180811_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.SlugField(max_length=250),
        ),
    ]
