# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-12 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180812_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.SlugField(error_messages={'required': 'Please enter letters and numbers only'}, max_length=250),
        ),
    ]
